# Generated by Django 5.0.2 on 2024-03-01 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('case_id', models.AutoField(primary_key=True, serialize=False)),
                ('case_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('lawyer_id', models.AutoField(primary_key=True, serialize=False)),
                ('lawyer_name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('contact_info', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('contact_info', models.CharField(max_length=255)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='client_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.client'),
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.IntegerField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(max_length=100)),
                ('upload_date', models.CharField(max_length=100)),
                ('case_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='lawyer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.lawyer'),
        ),
        migrations.CreateModel(
            name='LegalResearch',
            fields=[
                ('research_id', models.AutoField(primary_key=True, serialize=False)),
                ('research_topic', models.CharField(max_length=200)),
                ('researcher_name', models.CharField(max_length=200)),
                ('legal_caseid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.case')),
            ],
        ),
    ]
